### ISSUE TITLE
ModuleNotFoundError: No module named 'telethon"

### ISSUE THREAD

**Issue by sminato27** [daredevilkinng/Telegram-DM-Sender#1]
Help, pls

![image](https://user-images.githubusercontent.com/59450675/199837038-6183ca0a-9433-429a-8440-786d57a8f1e3.png)

![image](https://user-images.githubusercontent.com/59450675/199836932-3d7fdfc7-ae3c-4d82-bb87-2415f6778c48.png)

**Comment by daredevilkinng** [comment]
Hello there please ping on my address

https://t.me/daredevilkinng
